version: "3.8"

services:
  server:
    build:
      context: .  # Set context to root to ensure access to pointcloud.proto
      dockerfile: src/cpp/server/server.Dockerfile
    container_name: pointcloud_server_cpp
    ports:
      - "1111:1111"
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
      - ./results:/app/results
    environment:
      HOST: "0.0.0.0"
      PORT: "1111"
      EPS: "0.5"
      MIN_SAMPLES: "5"
      MAX_PERCENTILE: "95"
      MIN_PERCENTILE: "5"

  client:
    build:
      context: .  # Set context to root to ensure access to pointcloud.proto
      dockerfile: src/cpp/client/client.Dockerfile
    container_name: pointcloud_client_cpp
    depends_on:
      - server
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
      - ./results:/app/results
    environment:
      CLIENT_REMOTE_HOST: "pointcloud_server_cpp"
      CLIENT_REMOTE_PORT: "1111"
      CLIENT_INPUT_FILE: "data/oct-2-small.pcd"
      CLIENT_OUTPUT_FILE: "results/oct-2-small-output.labels"
      CLIENT_CHUNK_SIZE: "100"
