version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: src/python/server/server.Dockerfile
    container_name: pointcloud_server
    ports:
      - "1111:1111"
    volumes:
      - ./config.json:/app/config.json  # Flexible config file
      - ./data:/app/data                # Point cloud input data
      - ./results:/app/results          # Directory for results/output
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext", "localhost:1111", "list"]
      interval: 5s
      timeout: 3s
      retries: 3
    command: ["/bin/bash", "/app/server.sh", "--config=/app/config.json"]

  client:
    build:
      context: .
      dockerfile: src/python/client/client.Dockerfile
    container_name: pointcloud_client
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json  # Flexible config file
      - ./data:/app/data                # Point cloud input data
      - ./results:/app/results          # Directory for generated results/output
    command: ["/bin/bash", "/app/client.sh", "--config=/app/config.json"]
