FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    autoconf \
    automake \
    cmake \
    curl \
    g++ \
    git \
    libtool \
    make \
    pkg-config \
    unzip \
    curl \
    ca-certificates \
    pkg-config \
    libssl-dev \
    && apt-get clean

# Setup rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
